name: validate_adf

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  validate_adf_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js 18.x
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Debug: Check Node.js and npm version
      - name: Debug Node.js Version
        run: |
          node -v
          npm -v

      # Validate JSON structure of ADF resources
      - name: Validate ADF JSON files
        run: |
          find . -name "*.json" -exec jq empty {} \;
