name: ValidateADF

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  validate_adf:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      
      # Ensure Node.js 18.x is used
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Debug Node.js Version
        run: node -v  # Ensure it outputs v18.x

      - name: Validate Data Factory resources
        uses: Azure/data-factory-validate-action@v1.1.5
        with:
          path: ./
          id: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/batch15rsg/providers/Microsoft.DataFactory/factories/batch15-dev-adf-01
