name: ValidateADF

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  validate_adf:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: Validate Data Factory resources
        uses: Azure/data-factory-validate-action@v1.1.5
        with:
          path: ./
          id: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/batch15rsg/providers/Microsoft.DataFactory/factories/batch15-dev-adf-01
