name: ValidateADFJson

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  validate_adf_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Node.js 18.x
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Debug: Check Node.js and npm version
      - name: Debug Node.js Version
        run: |
          node -v
          npm -v

      # Validate JSON structure of ADF resources
      - name: Validate JSON Files
        run: |
          find . -name "*.json" -exec jq empty {} \;

      # Validate ADF JSON files using Microsoft Data Factory Utilities (No Azure Login)
      - name: Validate ADF Resources (Offline)
        run: |
          npx -y @microsoft/azure-data-factory-utilities validate ./
